tittle: "Bang Jago Dev"
description: "Catatan perjalanan gw switch karir ke IT"
author: "Pepri Andika"
email: "pepriandika@gmail.com"

# Kita pake tema bawaan Jekyll yang paling stabil buat Blog + Porto
theme: minima

# Settingan Navigasi (Biar rapi)
header_pages:
  - index.md
  - portfolio.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag